UI-MVC/Controllers/HomeController.cs
using System.Collections;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SC.UI.Web.MVC.Models;

namespace SC.UI.Web.MVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Login()
        {
            ViewData["Message"] = "Login";

            return View();
        }
        public IActionResult Swagger()
        {
            ViewData["Message"] = "Swagger";

            return Redirect("/swagger");
        }

        public IActionResult Authentication(string Id)
        {
            ViewData["Message"] = "Login";
            ArrayList users;
            users = Tools.getUserList();

            User selectedUser = null;

            foreach (User user in users)
            {
                if (int.TryParse(Id, out var result))
                    if (user.id == result)
                        selectedUser = user;

                if (user.name == Id) selectedUser = user;
            }

            if (selectedUser == null) return RedirectToAction("Login");

            if (selectedUser.admin)
            {
                var user = new DataHolder.user();
                user.name = selectedUser.name;
                user.admin = true;
                DataHolder.UserDataList.Add(user);
                return RedirectToAction("AdminChat", selectedUser);
            }

            var userClient = new DataHolder.user();
            userClient.name = selectedUser.name;
            userClient.admin = false;
            DataHolder.UserDataList.Add(userClient);

            return RedirectToAction("ClientChat", selectedUser);
        }

        public IActionResult ClientChat()
        {
            ViewData["Message"] = "Login";
            return View();
        }

        public IActionResult AdminChat()
        {
            ViewData["Message"] = "Login";
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel
            {
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            });
        }
    }
}

UI-MVC/Controllers/TicketController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using SC.BL;
using SC.BL.Domain;
using SC.UI.Web.MVC.Models;

namespace SC.UI.Web.MVC.Controllers
{
    public class TicketController : Controller
    {
        private ITicketManager mgr;

        public TicketController()
        {
            mgr = new TicketManager();
        }
        
        // GET: /Ticket
        public IActionResult Index()
        {
            IEnumerable<Ticket> tickets = mgr.GetTickets();
            return View(tickets);
        }
        
        // GET: /Ticket/Details/<ticket_number>
        public IActionResult Details(int id)
        {
            Ticket ticket = mgr.GetTicket(id);
            
            if(ticket.Responses != null)
                ViewBag.Responses = ticket.Responses;
            else
                ViewBag.Responses = mgr.GetTicketResponses(ticket.TicketNumber);
            
            return View(ticket);
        }
        
        // GET: /Ticket/Edit/<ticket_number>
        public IActionResult Edit(int id)
        {
            Ticket ticket = mgr.GetTicket(id);
            return View(ticket);
        }
        // POST: /Ticket/Edit/<ticket_number>
        [HttpPost]
        public IActionResult Edit(int id, Ticket ticket)
        {
            if(!ModelState.IsValid)
                return View(ticket);
            
            mgr.ChangeTicket(ticket);
            return RedirectToAction("Details", new {id = ticket.TicketNumber});
        }
        
        // GET: /Ticket/Create
        public IActionResult Create()
        {
            return View();
        }
        // POST: /Ticket/Create
        [HttpPost]
        public IActionResult Create(/*int accId, string problem*/CreateTicketViewModel createTicket)
        {
            Ticket newTicket = mgr.AddTicket(/*accId*/createTicket.AccId, /*problem*/createTicket.Problem);
            return RedirectToAction("Details", new {id = newTicket.TicketNumber});
        }
        
        // GET: /Ticket/Delete/<ticket_number>
        public IActionResult Delete(int id)
        {
            Ticket ticket = mgr.GetTicket(id);
            return View(ticket);
        }
        // POST: /Ticket/Delete/<ticket_number>
        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            mgr.RemoveTicket(id);
            return RedirectToAction("Index");
        }
    }
}

UI-MVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

UI-MVC/Views/Home/AdminChat.cshtml
@page
<div class="container">

    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-6">&nbsp;</div>
        <div class="col-6">

            <h3>message for global chat</h3>
            <input type="text" id="messageInput" placeholder="Message"/>
            <br/>
            <br/>
            <input type="button" id="sendButton" class="btn" value="Send Message"/>
            <br/>
            <br/>
            <h3>groupname to join/create or leave</h3>
            <input type="text" name="group-name" id="group-name" placeholder="Group name"/>
            <br/>
            <br/>
            <input type="button" id="join-group" class="btn" value="Join "/>
            <input type="button" id="leave-group" class="btn" value="Leave"/>
            <br/>
            <br/>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <hr/>
        </div>
    </div>
    <h3>Global chat</h3>
    <div class="row">
        <div class="col-6">&nbsp;</div>
        <div class="col-6">
            <ul id="messagesList"></ul>
        </div>
    </div>

    <h3>Group chat</h3>
    <div class="row">
        <div class="col-6">&nbsp;</div>
        <div class="col-6">
            <ul id="chats"></ul>
        </div>
    </div>
</div>
<script src="~/lib/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>

UI-MVC/Views/Home/ClientChat.cshtml
@page
<div class="container">
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-6">&nbsp;</div>
        <div class="col-6">
            <br/>
            <br/>
            <input type="text" id="messageInput" placeholder="Message"/>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <hr/>
        </div>
    </div>
    <h2>Global chat</h2>
    <div class="row">
        <div class="col-6">&nbsp;</div>
        <div class="col-6">
            <ul id="messagesList">

            </ul>
        </div>
    </div>
    <br/>
    <br/>
    <input type="button" id="sendButton" class="btn" value="Send Message"/>
    <br/>
    <h2>Chat with admin only</h2>
    <p id="myname"></p>
    <div class="row">
        <div class="col-6">&nbsp;</div>
        <div class="col-6">
            <ul id="messagesListclient">

            </ul>
        </div>
    </div>
    <br/>
    <br/>
    <input type="button" id="groupmsgclient" class="btn" value="Send to Group"/>
</div>
<script src="~/lib/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>

UI-MVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br/>
    Redmond, WA 98052-6399<br/>
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br/>
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

UI-MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "";
}

@*<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>*@
<div class="jumbotron">
    <h1>SupportCenter</h1>
    <p>Welkom op het online helpdesk systeem.</p>
</div>

@*<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>*@
<div class="row">
    <div class="col-md-4">
        <h2>Nieuw ticket</h2>
        <p>Maak een nieuw ticket aan in het systeem.</p>
        <a class="btn btn-default" @*href="#"*@ asp-controller="Ticket" asp-action="Create">Nieuw ticket</a>
    </div>
    <div class="col-md-4">
        <h2>Alle tickets</h2>
        <p>Toont een lijst van alle bestaande tickets.</p>
        <a class="btn btn-default" @*href="#"*@ asp-controller="Ticket" asp-action="Index">Alle tickets</a>
    </div>
    <div class="col-md-4">
        <h2>Toon ticket</h2>
        <p>Geeft de details van één ticket.</p>
        @*<a class="btn btn-default" href="#">Toon ticket</a>*@
        <form asp-controller="Ticket" asp-action="Details" method="get" class="form-inline">
            <input name="id" type="number" placeholder="Ticketnummer" class="form-control"/>
            <input type="submit" value="Toon ticket" class="btn btn-default"/>
        </form>
    </div>
</div>

UI-MVC/Views/Home/Login.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Login</title>
</head>
<body>
<br/>
<br/>
<div>
    <form asp-controller="Home" asp-action="Authentication" method="post">
        <div>
            <input name="Id" placeholder="Id of name">
            <input type="submit" class="btn" value="Login"/> | <a asp-action="Index">Annuleer</a>
        </div>
    </form>
</div>
</body>
</html>